//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaInventario.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public int configuracionID { get; set; }
        public string nombreEmpresa { get; set; }
        public string telefonoEmpresa { get; set; }
        public string IDFiscalempresa { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> IGTF { get; set; }
    }
}
