//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaInventario.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.ComprasDetalle = new HashSet<ComprasDetalle>();
            this.Stock = new HashSet<Stock>();
            this.VentasDetalle = new HashSet<VentasDetalle>();
        }
    
        public int productoID { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string codBarras { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<decimal> precioCompra { get; set; }
        public Nullable<decimal> precioVenta { get; set; }
        public Nullable<bool> estatus { get; set; }
        public Nullable<int> unidadMedidaID { get; set; }
        public Nullable<decimal> utilidad { get; set; }
        public Nullable<int> categoriaID { get; set; }
        public Nullable<bool> venderBajoCero { get; set; }
        public Nullable<decimal> nivelAlerta { get; set; }
        public Nullable<bool> exento { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComprasDetalle> ComprasDetalle { get; set; }
        public virtual UnidadesMedidas UnidadesMedidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentasDetalle> VentasDetalle { get; set; }
    }
}
