//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaInventario.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosPermisos
    {
        public int UsuarioPermisoID { get; set; }
        public Nullable<int> usuarioID { get; set; }
        public Nullable<bool> clientes { get; set; }
        public Nullable<bool> proveedores { get; set; }
        public Nullable<bool> categorias { get; set; }
        public Nullable<bool> stock { get; set; }
        public Nullable<bool> instrumentoPago { get; set; }
        public Nullable<bool> unidadMedida { get; set; }
        public Nullable<bool> configuracionGeneral { get; set; }
        public Nullable<bool> usuarios { get; set; }
        public Nullable<bool> productos { get; set; }
        public Nullable<bool> listadoCompras { get; set; }
        public Nullable<bool> nuevaCompra { get; set; }
        public Nullable<bool> listadoVenta { get; set; }
        public Nullable<bool> nuevaVenta { get; set; }
        public Nullable<bool> reportes { get; set; }
        public Nullable<bool> pestanaMantenimiento { get; set; }
        public Nullable<bool> pestanaCompras { get; set; }
        public Nullable<bool> pestanaVentas { get; set; }
        public Nullable<bool> pestanaReporte { get; set; }
        public Nullable<bool> monedas { get; set; }
        public Nullable<bool> respaldos { get; set; }
    
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
