//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaInventario.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasPago
    {
        public int ventaPagoID { get; set; }
        public Nullable<int> metodoPagoID { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<int> ventaID { get; set; }
        public Nullable<int> monedaID { get; set; }
        public Nullable<decimal> cambio { get; set; }
    
        public virtual MetodosPago MetodosPago { get; set; }
        public virtual Monedas Monedas { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
